export const BANNER_DATA = [
  {
    id: 1,
    thumbnailImage: '/banner/thumbnail-8.png',
    backgroundImage: '/banner/background-8.png',
    path: '/banner/background-8.png',
    backgroundMobile: '/banner/background-8-mobile.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 2,
    thumbnailImage: '/banner/thumbnail-9.png',
    backgroundImage: '/banner/background-9.png',
    path: '/banner/background-9.png',
    backgroundMobile: '/banner/background-9-mobile.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 3,
    thumbnailImage: '/banner/thumbnail-10.png',
    backgroundImage: '/banner/background-10.png',
    path: '/banner/background-10.png',
    backgroundMobile: '/banner/background-10-mobile.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      borderBottom: '400px solid transparent',
      borderLeft: '70px solid rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 4,
    thumbnailImage: '/banner/thumbnail-12.png',
    backgroundImage: '/banner/background-12.png',
    path: '/banner/background-12.png',
    backgroundMobile: '/banner/background-12-mobile.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: '#E20074',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      borderBottom: '400px solid transparent',
      borderLeft: '70px solid #E20074',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'secondary',
  },
  {
    id: 5,
    thumbnailImage: '/banner/thumbnail-15.png',
    backgroundImage: '/banner/background-15.png',
    path: '/banner/background-15.png',
    backgroundMobile: '/banner/background-15-mobile.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
    },
    contentRight: {
      flex: 1,
      height: '100%',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 6,
    thumbnailImage: '/banner/thumbnail-3.png',
    backgroundImage: '/banner/background-3.png',
    path: '/banner/background-3.png',
    backgroundMobile: '/banner/background-3-mobile.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 7,
    thumbnailImage: '/banner/thumbnail-2.png',
    backgroundImage: '/banner/background-2.png',
    path: '/banner/background-2.png',
    backgroundMobile: '/banner/background-2-mobile.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 8,
    thumbnailImage: '/banner/thumbnail-1.png',
    backgroundImage: '/banner/background-1.png',
    path: '/banner/background-1.png',
    backgroundMobile: '/banner/background-1-mobile.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 9,
    thumbnailImage: '/banner/thumbnail-4.png',
    backgroundImage: '/banner/background-4.png',
    path: '/banner/background-4.png',
    backgroundMobile: '/banner/background-4-mobile.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      borderBottom: '400px solid transparent',
      borderLeft: '70px solid rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 10,
    thumbnailImage: '/banner/thumbnail-13.png',
    backgroundImage: '/banner/background-13.png',
    path: '/banner/background-13.png',
    backgroundMobile: '/banner/background-13-mobile.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: '#E20074',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      borderBottom: '400px solid transparent',
      borderLeft: '70px solid #E20074',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'secondary',
  },
  {
    id: 11,
    thumbnailImage: '/banner/thumbnail-14.png',
    backgroundImage: '/banner/background-14.png',
    path: '/banner/background-14.png',
    backgroundMobile: '/banner/background-14-mobile.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: '#E20074',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      borderBottom: '400px solid transparent',
      borderLeft: '70px solid #E20074',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'secondary',
  },
  {
    id: 12,
    thumbnailImage: '/banner/thumbnail-6.png',
    backgroundImage: '/banner/background-6.png',
    path: '/banner/background-6.png',
    backgroundMobile: '/banner/background-6-mobile.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
    },
    contentRight: {
      flex: 1,
      height: '100%',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 13,
    thumbnailImage: '/banner/thumbnail-7.png',
    backgroundImage: '/banner/background-7.png',
    path: '/banner/background-7.png',
    backgroundMobile: '/banner/background-7-mobile.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
    },
    contentRight: {
      flex: 1,
      height: '100%',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },

  {
    id: 14,
    thumbnailImage: '/banner/l1-stage-telekom-security-desktop.png',
    backgroundImage: '/banner/l1-stage-telekom-security-desktop.png',
    path: '/banner/l1-stage-telekom-security-desktop.png',
    backgroundMobile: '/banner/l1-stage-telekom-security-desktop.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 15,
    thumbnailImage: '/banner/l2-stage-identity-security-desktop.png',
    backgroundImage: '/banner/l2-stage-identity-security-desktop.png',
    path: '/banner/l2-stage-identity-security-desktop.png',
    backgroundMobile: '/banner/l2-stage-identity-security-desktop.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 16,
    thumbnailImage: '/banner/l4-stage-magenta-security-business.id.png',
    backgroundImage: '/banner/l4-stage-magenta-security-business.id.png',
    path: '/banner/l4-stage-magenta-security-business.id.png',
    backgroundMobile: '/banner/l4-stage-magenta-security-business.id.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 17,
    thumbnailImage: '/banner/l4-stage-magenta-security-energy.id.png',
    backgroundImage: '/banner/l4-stage-magenta-security-energy.id.png',
    path: '/banner/l4-stage-magenta-security-energy.id.png',
    backgroundMobile: '/banner/l4-stage-magenta-security-energy.id.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 18,
    thumbnailImage: '/banner/l4-stage-magenta-security-iotm2m.id.png',
    backgroundImage: '/banner/l4-stage-magenta-security-iotm2m.id.png',
    path: '/banner/l4-stage-magenta-security-iotm2m.id.png',
    backgroundMobile: '/banner/l4-stage-magenta-security-iotm2m.id.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 19,
    thumbnailImage: '/banner/l4-stage-magenta-security-keymanagement.id.png',
    backgroundImage: '/banner/l4-stage-magenta-security-keymanagement.id.png',
    path: '/banner/l4-stage-magenta-security-keymanagement.id.png',
    backgroundMobile:
      '/banner/l4-stage-magenta-security-keymanagement.id.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 20,
    thumbnailImage: '/banner/l4-stage-magenta-security-onetimepass.id.png',
    backgroundImage: '/banner/l4-stage-magenta-security-onetimepass.id.png',
    path: '/banner/l4-stage-magenta-security-onetimepass.id.png',
    backgroundMobile: '/banner/l4-stage-magenta-security-onetimepass.id.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 21,
    thumbnailImage: '/banner/l4-stage-magenta-security-qualified.id.png',
    backgroundImage: '/banner/l4-stage-magenta-security-qualified.id.png',
    path: '/banner/l4-stage-magenta-security-qualified.id.png',
    backgroundMobile: '/banner/l4-stage-magenta-security-qualified.id.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 22,
    thumbnailImage: '/banner/l4-stage-magenta-security-secure-elements.png',
    backgroundImage: '/banner/l4-stage-magenta-security-secure-elements.png',
    path: '/banner/l4-stage-magenta-security-secure-elements.png',
    backgroundMobile: '/banner/l4-stage-magenta-security-secure-elements.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 23,
    thumbnailImage: '/banner/l4-stage-magenta-security-server.id.png',
    backgroundImage: '/banner/l4-stage-magenta-security-server.id.png',
    path: '/banner/l4-stage-magenta-security-server.id.png',
    backgroundMobile: '/banner/l4-stage-magenta-security-server.id.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 24,
    thumbnailImage: '/banner/l4-stage-magenta-security-smartcard.png',
    backgroundImage: '/banner/l4-stage-magenta-security-smartcard.png',
    path: '/banner/l4-stage-magenta-security-smartcard.png',
    backgroundMobile: '/banner/l4-stage-magenta-security-smartcard.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 25,
    thumbnailImage: '/banner/l5-stage-downloads-funktionsweise.png',
    backgroundImage: '/banner/l5-stage-downloads-funktionsweise.png',
    path: '/banner/l5-stage-downloads-funktionsweise.png',
    backgroundMobile: '/banner/l5-stage-downloads-funktionsweise.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 26,
    thumbnailImage: '/banner/l5-stage-pki-repository.png',
    backgroundImage: '/banner/l5-stage-pki-repository.png',
    path: '/banner/l5-stage-pki-repository.png',
    backgroundMobile: '/banner/l5-stage-pki-repository.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 27,
    thumbnailImage: '/banner/l5-stage-rechtssicherheit.png',
    backgroundImage: '/banner/l5-stage-rechtssicherheit.png',
    path: '/banner/l5-stage-rechtssicherheit.png',
    backgroundMobile: '/banner/l5-stage-rechtssicherheit.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 28,
    thumbnailImage: '/banner/l5-stage-root-programm.png',
    backgroundImage: '/banner/l5-stage-root-programm.png',
    path: '/banner/l5-stage-root-programm.png',
    backgroundMobile: '/banner/l5-stage-root-programm.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 29,
    thumbnailImage: '/banner/l5-stage-service-kompetenzen.png',
    backgroundImage: '/banner/l5-stage-service-kompetenzen.png',
    path: '/banner/l5-stage-service-kompetenzen.png',
    backgroundMobile: '/banner/l5-stage-service-kompetenzen.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 30,
    thumbnailImage: '/banner/l5-stage-service-prevent.png',
    backgroundImage: '/banner/l5-stage-service-prevent.png',
    path: '/banner/l5-stage-service-prevent.png',
    backgroundMobile: '/banner/l5-stage-service-prevent.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 31,
    thumbnailImage: '/banner/l5-stage-support-faq.png',
    backgroundImage: '/banner/l5-stage-support-faq.png',
    path: '/banner/l5-stage-support-faq.png',
    backgroundMobile: '/banner/l5-stage-support-faq.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 32,
    thumbnailImage: '/banner/l5-stage-support-unterstutzung.png',
    backgroundImage: '/banner/l5-stage-support-unterstutzung.png',
    path: '/banner/l5-stage-support-unterstutzung.png',
    backgroundMobile: '/banner/l5-stage-support-unterstutzung.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 33,
    thumbnailImage: '/banner/Banner_Allgemein_SP.png',
    backgroundImage: '/banner/Banner_Allgemein_SP.png',
    path: '/banner/Banner_Allgemein_SP.png',
    backgroundMobile: '/banner/Banner_Allgemein_SP.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 34,
    thumbnailImage: '/banner/Banner_Datenschutz_SP.png',
    backgroundImage: '/banner/Banner_Datenschutz_SP.png',
    path: '/banner/Banner_Datenschutz_SP.png',
    backgroundMobile: '/banner/Banner_Datenschutz_SP.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 35,
    thumbnailImage: '/banner/Banner_Downloads_SP.png',
    backgroundImage: '/banner/Banner_Downloads_SP.png',
    path: '/banner/Banner_Downloads_SP.png',
    backgroundMobile: '/banner/Banner_Downloads_SP.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 36,
    thumbnailImage: '/banner/Banner_Impressum_SP.png',
    backgroundImage: '/banner/Banner_Impressum_SP.png',
    path: '/banner/Banner_Impressum_SP.png',
    backgroundMobile: '/banner/Banner_Impressum_SP.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 37,
    thumbnailImage: '/banner/Banner_Kontakt_SP.png',
    backgroundImage: '/banner/Banner_Kontakt_SP.png',
    path: '/banner/Banner_Kontakt_SP.png',
    backgroundMobile: '/banner/Banner_Kontakt_SP.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 38,
    thumbnailImage: '/banner/Banner_Karriere_SP.png',
    backgroundImage: '/banner/Banner_Karriere_SP.png',
    path: '/banner/Banner_Karriere_SP.png',
    backgroundMobile: '/banner/Banner_Karriere_SP.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 39,
    thumbnailImage: '/banner/Banner_News_SP.png',
    backgroundImage: '/banner/Banner_News_SP.png',
    path: '/banner/Banner_News_SP.png',
    backgroundMobile: '/banner/Banner_News_SP.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 40,
    thumbnailImage: '/banner/Banner_Repository_SP.png',
    backgroundImage: '/banner/Banner_Repository_SP.png',
    path: '/banner/Banner_Repository_SP.png',
    backgroundMobile: '/banner/Banner_Repository_SP.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 41,
    thumbnailImage: '/banner/Banner_Support_SP.png',
    backgroundImage: '/banner/Banner_Support_SP.png',
    path: '/banner/Banner_Support_SP.png',
    backgroundMobile: '/banner/Banner_Support_SP.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 42,
    thumbnailImage: '/banner/Banner_Home_SP.png',
    backgroundImage: '/banner/Banner_Home_SP.png',
    path: '/banner/Banner_Home_SP.png',
    backgroundMobile: '/banner/Banner_Home_SP.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },

  {
    id: 43,
    thumbnailImage: '/banner/aktuelles_tsec_desktop.png',
    backgroundImage: '/banner/aktuelles_tsec_desktop.png',
    path: '/banner/aktuelles_tsec_desktop.png',
    backgroundMobile: '/banner/aktuelles_tsec_mobil.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 44,
    thumbnailImage: '/banner/automatisierung_tsec_desktop.png',
    backgroundImage: '/banner/automatisierung_tsec_desktop.png',
    path: '/banner/automatisierung_tsec_desktop.png',
    backgroundMobile: '/banner/automatisierung_tsec_mobil.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 45,
    thumbnailImage: '/banner/datenschutz_tsec_desktop.png',
    backgroundImage: '/banner/datenschutz_tsec_desktop.png',
    path: '/banner/datenschutz_tsec_desktop.png',
    backgroundMobile: '/banner/datenschutz_tsec_mobil.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 46,
    thumbnailImage: '/banner/download_tsec_desktop.png',
    backgroundImage: '/banner/download_tsec_desktop.png',
    path: '/banner/download_tsec_desktop.png',
    backgroundMobile: '/banner/download_tsec_mobil.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 47,
    thumbnailImage: '/banner/home_tsec_desktop.png',
    backgroundImage: '/banner/home_tsec_desktop.png',
    path: '/banner/home_tsec_desktop.png',
    backgroundMobile: '/banner/home_tsec_mobil.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 48,
    thumbnailImage: '/banner/home_uberuns_tsec_desktop.png',
    backgroundImage: '/banner/home_uberuns_tsec_desktop.png',
    path: '/banner/home_uberuns_tsec_desktop.png',
    backgroundMobile: '/banner/home_uberuns_tsec_mobil.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 49,
    thumbnailImage: '/banner/impressum_tsec_desktop.png',
    backgroundImage: '/banner/impressum_tsec_desktop.png',
    path: '/banner/impressum_tsec_desktop.png',
    backgroundMobile: '/banner/impressum_tsec_mobil.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 50,
    thumbnailImage: '/banner/karriere_tsec_desktop.png',
    backgroundImage: '/banner/karriere_tsec_desktop.png',
    path: '/banner/karriere_tsec_desktop.png',
    backgroundMobile: '/banner/karriere_tsec_mobil.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 52,
    thumbnailImage: '/banner/kontakt_tsec_desktop.png',
    backgroundImage: '/banner/kontakt_tsec_desktop.png',
    path: '/banner/kontakt_tsec_desktop.png',
    backgroundMobile: '/banner/kontakt_tsec_mobil.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 53,
    thumbnailImage: '/banner/l2_consulting_tsec_desktop.png',
    backgroundImage: '/banner/l2_consulting_tsec_desktop.png',
    path: '/banner/l2_consulting_tsec_desktop.png',
    backgroundMobile: '/banner/l2_consulting_tsec_mobil.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 54,
    thumbnailImage: '/banner/l2_cyber_defense_tsec_desktop.png',
    backgroundImage: '/banner/l2_cyber_defense_tsec_desktop.png',
    path: '/banner/l2_cyber_defense_tsec_desktop.png',
    backgroundMobile: '/banner/l2_cyber_defense_tsec_mobil.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 55,
    thumbnailImage: '/banner/l2_identity_tsec_desktop.png',
    backgroundImage: '/banner/l2_identity_tsec_desktop.png',
    path: '/banner/l2_identity_tsec_desktop.png',
    backgroundMobile: '/banner/l2_identity_tsec_mobil.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 56,
    thumbnailImage: '/banner/l2_infrastructure_tsec_desktop.png',
    backgroundImage: '/banner/l2_infrastructure_tsec_desktop.png',
    path: '/banner/l2_infrastructure_tsec_desktop.png',
    backgroundMobile: '/banner/l2_infrastructure_tsec_mobil.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 57,
    thumbnailImage: '/banner/l4_clientID_tsec_desktop.png',
    backgroundImage: '/banner/l4_clientID_tsec_desktop.png',
    path: '/banner/l4_clientID_tsec_desktop.png',
    backgroundMobile: '/banner/l4_clientID_tsec_mobil.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 58,
    thumbnailImage: '/banner/l4_serverID_tsec_desktop.png',
    backgroundImage: '/banner/l4_serverID_tsec_desktop.png',
    path: '/banner/l4_serverID_tsec_desktop.png',
    backgroundMobile: '/banner/l4_serverID_tsec_mobil.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 59,
    thumbnailImage: '/banner/l4_smartcards_tsec_desktop.png',
    backgroundImage: '/banner/l4_smartcards_tsec_desktop.png',
    path: '/banner/l4_smartcards_tsec_desktop.png',
    backgroundMobile: '/banner/l4_smartcards_tsec_mobil.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 60,
    thumbnailImage: '/banner/modularitat_tsec_desktop.png',
    backgroundImage: '/banner/modularitat_tsec_desktop.png',
    path: '/banner/modularitat_tsec_desktop.png',
    backgroundMobile: '/banner/modularitat_tsec_mobil.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 61,
    thumbnailImage: '/banner/optimierung_tsec_desktop.png',
    backgroundImage: '/banner/optimierung_tsec_desktop.png',
    path: '/banner/optimierung_tsec_desktop.png',
    backgroundMobile: '/banner/optimierung_tsec_mobil.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 62,
    thumbnailImage: '/banner/shop_tsec_desktop.png',
    backgroundImage: '/banner/shop_tsec_desktop.png',
    path: '/banner/shop_tsec_desktop.png',
    backgroundMobile: '/banner/shop_tsec_mobil.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 63,
    thumbnailImage: '/banner/support_tsec_desktop.png',
    backgroundImage: '/banner/support_tsec_desktop.png',
    path: '/banner/support_tsec_desktop.png',
    backgroundMobile: '/banner/support_tsec_mobil.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 64,
    thumbnailImage: '/banner/verfugbar_tsec_desktop.png',
    backgroundImage: '/banner/verfugbar_tsec_desktop.png',
    path: '/banner/verfugbar_tsec_desktop.png',
    backgroundMobile: '/banner/verfugbar_tsec_mobil.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 65,
    thumbnailImage: '/banner/vertrag_tsec_desktop.png',
    backgroundImage: '/banner/vertrag_tsec_desktop.png',
    path: '/banner/vertrag_tsec_desktop.png',
    backgroundMobile: '/banner/vertrag_tsec_mobil.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 66,
    thumbnailImage: '/banner/vielseitig_tsec_desktop.png',
    backgroundImage: '/banner/vielseitig_tsec_desktop.png',
    path: '/banner/vielseitig_tsec_desktop.png',
    backgroundMobile: '/banner/vielseitig_tsec_mobil.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
  {
    id: 67,
    thumbnailImage: '/banner/zukunftssicher_tsec_desktop.png',
    backgroundImage: '/banner/zukunftssicher_tsec_desktop.png',
    path: '/banner/zukunftssicher_tsec_desktop.png',
    backgroundMobile: '/banner/zukunftssicher_tsec_mobil.png',
    layersStyle: {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      width: '100%',
      color: '#FFF',
      display: 'flex',
    },
    contentLeft: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    contentRight: {
      flex: 1,
      height: '100%',
      background: 'rgba(0, 0, 0, 0.48)',
    },
    title: {
      fontFamily: 'TeleNeoWeb',
      fontWeight: '700',
      fontSize: '2rem',
      color: '#FFFFFF',
      marginBottom: '1rem',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    description: {
      fontSize: '20px',
      fontStyle: 'italic',
      color: '#FFFFFF',
      marginBottom: '24px',
      maxHeight: '3.6em',
      lineHeight: '1.2em',
      display: '-webkit-box !important',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    variant: 'primary',
  },
];
